import os


LAND_PROBABILITY = 0.425
SMOOTHING_ITERATIONS = 8
# Grid
ROWS = 150
COLS = 150
# Pygame
WIDTH = 750
HEIGHT = 750
DATAPATH = "data/grid.json"
# Boat
BOAT_STARTING_POS = 0, 0
BOAT_TARGET_POS = (ROWS - 1, COLS - 1)
# Other
RANDOMIZE_TARGET_POS = True
REPLACE_DATA = True
PYGAME_TITLE = "FLL Double Minus innovation project"

